import { PermissionKey } from '@/types';

export const PERMISSION_CATALOG: PermissionKey[] = [
  'company.read',
  'company.update',
  'roles.read',
  'roles.create',
  'roles.update',
  'roles.delete',
  'branches.read',
  'branches.create',
  'branches.update',
  'branches.delete',
  'orgUnits.read',
  'orgUnits.create',
  'orgUnits.update',
  'orgUnits.delete',
  'positions.read',
  'positions.create',
  'positions.update',
  'positions.delete',
  'employees.read',
  'employees.create',
  'employees.update',
  'employees.delete',
  'employees.assignManager',
  'parties.read',
  'parties.create',
  'parties.update',
  'parties.delete',
  'contacts.read',
  'contacts.create',
  'contacts.update',
  'contacts.delete',
  'audit.read',
];

export const PERMISSION_GROUPS: Array<{ label: string; items: PermissionKey[] }> = [
  { label: 'Cong ty', items: ['company.read', 'company.update'] },
  { label: 'Vai tro', items: ['roles.read', 'roles.create', 'roles.update', 'roles.delete'] },
  { label: 'Chi nhanh', items: ['branches.read', 'branches.create', 'branches.update', 'branches.delete'] },
  { label: 'Don vi to chuc', items: ['orgUnits.read', 'orgUnits.create', 'orgUnits.update', 'orgUnits.delete'] },
  { label: 'Chuc danh', items: ['positions.read', 'positions.create', 'positions.update', 'positions.delete'] },
  {
    label: 'Nhan vien',
    items: ['employees.read', 'employees.create', 'employees.update', 'employees.delete', 'employees.assignManager'],
  },
  { label: 'Doi tac', items: ['parties.read', 'parties.create', 'parties.update', 'parties.delete'] },
  { label: 'Lien he', items: ['contacts.read', 'contacts.create', 'contacts.update', 'contacts.delete'] },
  { label: 'Kiem toan', items: ['audit.read'] },
];
